import { Footer } from "@/components/footer";
import { NavbarComponent } from "@/components/navbar";
import { siteConfig } from "@/config/site";
import "@/styles/globals.css";
import clsx from "clsx";
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
	title: {
		default: "VPS FiveM com DDoS, Ping Baixo e txAdmin — Hospedagem Gamer Profissional",
		template: "%s | NeonHost",
	},
	description:
		"Hospede seu servidor GTA RP com proteção DDoS, instalação automática de txAdmin, e suporte a ESX/vRP. VPS Gamer com ping baixo em São Paulo..",
	keywords: [
    "NeonHost",
    "BrasilFivemHost",
    "fivemhost",
    "Fivem Host",
    "bbhost",
    "BBHost",
    "BBHOST",
    "WyzeHost",
    "TynaHost",
    "Hostinger",
    "DokeHost",
    "HeavyHost",
    "OminiHost",
    "BH Servers",
    "Ultahost",
    "KnownHost",
    "Linode",
    "DigitalOcean",
    "Azure",
    "Namecheap",
    "NetEarthOne",
    "FlameHost",
    "RazeHost",
    "Loding Hosting",
    "Nice Hosting",
    "VPS Neon",
    "VPS Brasil",
    "Proteção Anti DDoS",
    "servidor de Minecraft",
    "servidor de FiveM",
    "servidor de Rust",
    "hospedagem de jogos no Brasil",
    "servidor dedicado para jogos",
    "servidor de ARK",
    "servidor de Satisfactory",
    "VPS para jogos",
    "servidores dedicados Brasil",
    "gaming VPS",
    "FiveM VPS",
    "Minecraft VPS",
    "VPS com NVMe",
    "servidor de Counter Strike",
    "servidor de CS:GO",
    "servidor de GTA RP",
    "servidor de Unturned",
    "VPS Linux",
    "VPS Windows",
    "servidor com proteção DDoS",
    "cloud gaming",
    "hospedagem de jogos multiplayer",
    "servidor dedicado gamer",
    "servidor de Minecraft Brasil",
    "VPS com alta performance",
    "VPS barato",
    "VPS para trading",
    "servidor dedicado NVMe",
    "cloud hosting",
    "FlameHost",
    "RazeHost",
    "Loding Hosting",
    "Nice Hosting",
    "wyze",
    "wyze host",
    "host",
    "ddos",
    "webhost",
    "hospedagem",
    "site",
    "vps",
    "vps gamer",
    "gaming vps",
    "vps",
    "semi dedicado",
    "servidor dedicado",
    "teamspeak",
    "team-speak",
    "team-speak 3 server",
    "proteção ddos",
    "server",
    "servidor",
    "servidor",
    "serviço de hospedagem",
    "hospedagem brasil",
    "host brasileira",
    "host 0ms",
    "melhor host do brasil",
    "onde hospedar",
    "como hospedar um site",
    "como hospedar um site",
    "como hospedar fivem",
    "host de jogo",
    "vrising",
    "como criar servidor de vrising",
    "como criar servidor de gta rp",
    "como criar servidor de fivem",
    "como criar servidor de cidade fivem",
    "como criar servidor de cidade fivem rp",
    "jogar vrising online",
    "vrising online",
    "melhor servidor vrising",
    "vrising server",
    "host fivem",
    "hospedagem de fivem",
    "fivem",
    "host minecraft",
    "hospedagem minecraft",
    "minecraft",
    "como deixar fivem online 24 horas",
    "criar cidade fivem",
    "cidade",
    "host de fivem",
    "host gta rp",
    "hospedagem para gta rp",
    "host fivem br",
    "fivem host",
    "ddos",
    "proteção ddos",
    "anti-ddos",
    "Hostzone",
    "Hostinger",
    "HeavyHost",
    "BH Servers",
    "Ultahost",
    "KnownHost",
    "Linode",
    "DigitalOcean",
    "Azure",
    "Namecheap",
    "NetEarthOne",
    "FlameHost",
    "RazeHost",
    "Loding Hosting",
    "Nice Hosting",
    "VPS Neon",
    "VPS Brasil",
    "Proteção Anti DDoS",
    "servidor de Minecraft",
    "servidor de FiveM",
    "servidor de Rust",
    "hospedagem de jogos no Brasil",
    "servidor dedicado para jogos",
    "servidor de ARK",
    "servidor de Satisfactory",
    "VPS para jogos",
    "servidores dedicados Brasil",
    "gaming VPS",
    "FiveM VPS",
    "Minecraft VPS",
    "VPS com NVMe",
    "servidor de Counter Strike",
    "servidor de CS:GO",
    "servidor de GTA RP",
    "servidor de Unturned",
    "VPS Linux",
    "VPS Windows",
    "servidor com proteção DDoS",
    "cloud gaming",
    "hospedagem de jogos multiplayer",
    "servidor dedicado gamer",
    "servidor de Minecraft Brasil",
    "VPS com alta performance",
    "VPS barato",
    "VPS para trading",
    "servidor dedicado NVMe",
    "cloud hosting",
    "cache externo",
    "cache externo fivem",
    "cache externo gtarp",
    "cache-externo",
    "cache-externo fivem",
    "cache-externo gtarp",
    "cache-externo vps",
    "cache-externo vps gamer",
    "cache externo vps",
    "cache externo vps gamer",
    "cache externo redm",
    "cache externo rd2",
    "host de redm",
    "vps redm",
    "vps rd2",
    "Vps Redm",
    "Vps Gamer",
    "Vps gamer",
    "vps gamer",
    "Servidor VPS Gamer",
    "Servidor Vps Gamer",
    "Servidor Gamer",
    "Steam",
    "Steam Games",
    "Steam VPS",
    "VPS Azure",
    "Google Cloud",
    "vps barato",
    "comprar vps",
    "servidor vps brasil",
    "vps windows barato",
    "melhor vps 2025",
    "vps vs dedicado",
    "vps cloud brasil",
    "vps são paulo",
    "vps rio de janeiro",
    "datacenter brasil",
    "hospedagem servidor minecraft",
    "servidor minecraft barato",
    "free minecraft server hosting",
    "hospedagem fivem",
    "vps fivem ddos",
    "servidor gta rp host",
    "servidor rust brasil",
    "ark server hosting",
    "valheim server brasileiro",
    "game server hosting",
    "low latency vps",
    "ddos protection gamer",
    "como criar servidor minecraft 24/7 vps",
    "vps linux para jogos com painel pterodactyl",
    "vps gamer com proteção ddos grátis",
    "comprar vps barato com ping baixo brasil",
    "vps fivem barato",
    "hospedagem fivem ddos",
    "vps para gta rp",
    "vps redm brasil",
    "vps para redm brasil",
    "vps para redm",
    "servidor gta rp host",
    "hospedar servidor redm",
    "como criar servidor fivem com vps",
    "melhor vps para fivem 2025",
    "vps com proteção ddos para gta rp",
    "hospedagem redm com painel txadmin",
    "vps fivem ping baixo brasil",
    "top 10 melhores host fivem",
		"top 10 melhores vps gamer",
		"As top 10 melhores vps gamer",
		"As top 10 melhores vps fivem",
		"As top 10 melhores host fivem",
		"NeonHost",
		"WyzeHost",
		"TynaHost",
		"Hostinger",
		"DokeHost",
		"HeavyHost",
		"OminiHost",
		"BH Servers",
		"Ultahost",
		"KnownHost",
		"Linode",
		"DigitalOcean",
		"Azure",
		"Namecheap",
		"NetEarthOne",
		"FlameHost",
		"RazeHost",
		"Loding Hosting",
		"Nice Hosting",
		"VPS Gamer",
		"VPS Brasil",
		"Proteção Anti DDoS",
		"servidor de Minecraft",
		"servidor de FiveM",
		"servidor de Rust",
		"hospedagem de jogos no Brasil",
		"servidor dedicado para jogos",
		"servidor de ARK",
		"servidor de Satisfactory",
		"VPS para jogos",
		"servidores dedicados Brasil",
		"gaming VPS",
		"FiveM VPS",
		"Minecraft VPS",
		"VPS com NVMe",
		"servidor de Counter Strike",
		"servidor de CS:GO",
		"servidor de GTA RP",
		"servidor de Unturned",
		"VPS Linux",
		"VPS Windows",
		"servidor com proteção DDoS",
		"cloud gaming",
		"hospedagem de jogos multiplayer",
		"servidor dedicado gamer",
		"servidor de Minecraft Brasil",
		"VPS com alta performance",
		"VPS barato",
		"VPS para trading",
		"servidor dedicado NVMe",
		"cloud hosting",
		"FlameHost",
		"RazeHost",
		"Loding Hosting",
		"Nice Hosting",
		"Hostzone",
		"Hostinger",
		"HeavyHost",
		"BH Servers",
		"Ultahost",
		"KnownHost",
		"Linode",
		"DigitalOcean",
		"Azure",
		"Namecheap",
		"NetEarthOne",
		"FlameHost",
		"fivem",
		"Fivem",
		"Fivem VPS",
		"Melhores VPS Fivem",
		"Melhores VPS FiveM",
		"Melhores VPS FiveM Brasil",
		"Melhores VPS FiveM Brasil 2024",
		"Melhores VPS FiveM Brasil 2025",
		"Melhores VPS Gamer",
		"Melhores VPS Gamer Brasil",
		"Melhores VPS Gamer Brasil 2024",
		"Melhores VPS Gamer Brasil 2025",
		"Melhores VPS 2024",
		"Melhores VPS 2025",
		"Melhores VPS Brasil",
		"NeonHost",
		"Neonhost",
		"Servidores Dedicados",
		"Servidores Dedicados Brasil",
		"Servidores Dedicados Brasil 2024",
		"Servidores Dedicados Brasil 2025",
		"Host Rust",
		"Host Rust Brasil",
		"Host Rust Brasil 2024",
		"Host Rust Brasil 2025",
		"Host Terraria",
		"Host Terraria Brasil",
		"Host Terraria Brasil 2024",
		"Host Terraria Brasil 2025",
		"Host Minecraft",
		"Host Minecraft Brasil",
		"Host Minecraft Brasil 2024",
		"Host Minecraft Brasil 2025",
		"vps",
		"vps gamer",
		"vps gamer Brasil",
		"vps gamer Brasil 2024",
		"vps gamer Brasil 2025",
		"fivem brasil",
		"fivem brasil 2024",
		"fivem brasil 2025",
		"fivem host",
		"fivem host Brasil",
		"fivem host Brasil 2024",
		"fivem host Brasil 2025",
		"vps para fivem",
		"vps para fivem Brasil",
		"vps para jogos",
		"vps para jogos Brasil",
		"vps para jogos Brasil 2024",
		"host para dayz",
		"host para dayz Brasil",
		"host para dayz Brasil 2024",
		"host para dayz Brasil 2025",
		"cloud vps",
		"cloud vps Brasil",
		"cloud vps Brasil 2024",
		"cloud vps Brasil 2025",
		"cloud vps gamer",
		"cloud vps gamer Brasil",
		"cloud vps gamer Brasil 2024",
		"cloud vps gamer Brasil 2025",
		"host para ragnarok",
		"host para ragnarok Brasil",
		"host para ragnarok Brasil 2024",
		"host para ragnarok Brasil 2025",
		"bbhost",
		"bbhost",
		"bb host",
		"host",
		"host de jogos",
		"host de jogos Brasil",
		"host de jogos Brasil 2024",
		"host de jogos Brasil 2025",
		"host para jogos",
		"host para jogos Brasil",
		"host para jogos Brasil 2024",
		"fivem host brasil",
		"fivem host brasil 2024",
		"fivem host brasil 2025",
		"host fivembrasil",
		"fivem host",
		"fivem brasil host",
		"host para ark",
		"vps",
		"vps brasil",
		"vps no brasil",
		"vps gamer",
		"servidores",
		"servidores vps",
		"servidores vps brasil",
		"vps barata",
		"vps windows",
		"vps linux",
		"virtual maquina",
		"virtual maquina brasil",
		"virtual maquina brasil 2024",
		"virtual maquina brasil 2025",
		"anti ddos",
		"anti ddos brasil",
		"anti ddos brasil 2024",
		"anti ddos brasil 2025",
		"antiddos",
		"anti-ddos",
		"melhor protecao para fivem",
		"melhor protecao para fivem brasil",
		"melhor protecao para fivem brasil 2024",
		"melhor protecao para fivem brasil 2025",
		"fivem",
		"fivem brasil",
		"gta v host",
		"gta host",
		"gta host brasil",
		"gta host brasil 2024",
		"gta host brasil 2025",
		"mta",
		"mta brasil",
		"mta brasil 2024",
		"mta brasil 2025",
		"servidores dedicados",
		"dedicado",
		"dedicados",
		"baremetal",
		"baremetal brasil",
		"baremetal brasil 2024",
		"baremetal brasil 2025",
		"datacenter br",
		"datacenter brasil",
		"datacenter brasil 2024",
		"datacenter brasil 2025",
		"brasil",
		"o que é vps",
		"RazeHost",
		"Loding Hosting",
		"Nice Hosting",
		"VPS Gamer",
		"VPS Brasil",
		"Proteção Anti DDoS",
		"servidor de Minecraft",
		"servidor de FiveM",
		"servidor de Rust",
		"hospedagem de jogos no Brasil",
		"servidor dedicado para jogos",
		"servidor de ARK",
		"servidor de Satisfactory",
		"VPS para jogos",
		"servidores dedicados Brasil",
		"gaming VPS",
		"FiveM VPS",
		"Minecraft VPS",
		"VPS com NVMe",
		"servidor de Counter Strike",
		"servidor de CS:GO",
		"servidor de GTA RP",
		"servidor de Unturned",
		"VPS Linux",
		"VPS Windows",
		"servidor com proteção DDoS",
		"cloud gaming",
		"hospedagem de jogos multiplayer",
		"servidor dedicado gamer",
		"servidor de Minecraft Brasil",
		"VPS com alta performance",
		"VPS barato",
		"VPS para trading",
		"servidor dedicado NVMe",
		"cloud hosting",
		"cache externo",
		"cache externo fivem",
		"cache externo gtarp",
		"cache-externo",
		"cache-externo fivem",
		"cache-externo gtarp",
		"cache-externo vps",
		"cache-externo vps gamer",
		"cache externo vps",
		"cache externo vps gamer",
		"vps",
		"TacoHost",
		"Neopixelhost",
  ],

	openGraph: {
		type: "website",
		locale: "pt_BR",
		url: "https://neonhost.com.br/fivem",
		title: "VPS FiveM com DDoS, Ping Baixo e txAdmin — Hospedagem Gamer Profissional",
		description:
			"Hospede seu servidor GTA RP com proteção DDoS, instalação automática de txAdmin, e suporte a ESX/vRP. VPS Gamer com ping baixo em São Paulo.",
		siteName: "NeonHost",
		images: [
			{
				url: "/NeonHost.jpg",
				width: 1280,
				height: 630,
				alt: "NeonHost - Hospedagem de Jogos no Brasil",
			},
		],
	},
	robots: {
		index: true,
		follow: true,
		googleBot: {
			index: true,
			follow: true,
			"max-video-preview": -1,
			"max-image-preview": "large",
			"max-snippet": -1,
		},
	},
	twitter: {
		title: "VPS FiveM com DDoS, Ping Baixo e txAdmin — Hospedagem Gamer Profissional",
		card: "summary_large_image",
		description:
			"Hospede seu servidor GTA RP com proteção DDoS, instalação automática de txAdmin, e suporte a ESX/vRP. VPS Gamer com ping baixo em São Paulo.",
		images: ["/NeonHost.jpg"],
	},
	alternates: {
		canonical: "https://neonhost.com.br/fivem",
	},
};

export const viewport: Viewport = {
	themeColor: [
		{ media: "(prefers-color-scheme: light)", color: "white" },
		{ media: "(prefers-color-scheme: dark)", color: "black" },
	],
};

const inter = Inter({ subsets: ["latin"] });

export default function VpsGamerLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return <>{children}</>;
}
