export const plans = [
  {
    name: "FiveM Start",
    price: "49,90",
    link: "https://app.neonhost.com.br/index.php?rp=/store/fivem-start",
    description: {
      ram: "2GB",
      cores: "2 núcleos",
      ssd: "40GB",
      attrs: [
        "Anti-DDoS Incluído",
        "Painel de Controle",
        "Suporte 24/7",
        "Instalação Gratuita",
        "Até 32 jogadores",
        "Uptime 99.9%",
      ],
    },
  },
  {
    name: "FiveM Plus",
    price: "69,90",
    link: "https://app.neonhost.com.br/index.php?rp=/store/fivem-plus",
    description: {
      ram: "4GB",
      cores: "2 núcleos",
      ssd: "50GB",
      attrs: [
        "Anti-DDoS Incluído",
        "Painel de Controle",
        "Suporte 24/7",
        "Instalação Gratuita",
        "Até 64 jogadores",
        "Backup Semanal",
        "Uptime 99.9%",
      ],
    },
  },
  {
    name: "FiveM Pro",
    price: "99,90",
    link: "https://app.neonhost.com.br/index.php?rp=/store/fivem-pro",
    description: {
      ram: "6GB",
      cores: "3 núcleos",
      ssd: "60GB",
      attrs: [
        "Anti-DDoS Incluído",
        "Painel de Controle",
        "Suporte 24/7",
        "Instalação Gratuita",
        "Até 96 jogadores",
        "Backup Semanal",
        "Uptime 99.9%",
        "Prioridade no Suporte",
      ],
    },
  },
  {
    name: "FiveM Ultra",
    price: "149,90",
    link: "https://app.neonhost.com.br/index.php?rp=/store/fivem-ultra",
    description: {
      ram: "8GB",
      cores: "4 núcleos",
      ssd: "70GB",
      attrs: [
        "Anti-DDoS Incluído",
        "Painel de Controle",
        "Suporte 24/7",
        "Instalação Gratuita",
        "Até 128 jogadores",
        "Backup Semanal",
        "Uptime 99.9%",
        "Prioridade no Suporte",
        "Migração Gratuita",
      ],
    },
  },
  {
    name: "FiveM Extreme",
    price: "199,90",
    link: "https://app.neonhost.com.br/index.php?rp=/store/fivem-extreme",
    description: {
      ram: "12GB",
      cores: "6 núcleos",
      ssd: "80GB",
      attrs: [
        "Anti-DDoS Incluído",
        "Painel de Controle",
        "Suporte 24/7",
        "Instalação Gratuita",
        "Até 196 jogadores",
        "Backup Semanal",
        "Uptime 99.9%",
        "Prioridade no Suporte",
        "Migração Gratuita",
        "IP Dedicado",
      ],
    },
  },
  {
    name: "FiveM Titan",
    price: "249,90",
    link: "https://app.neonhost.com.br/index.php?rp=/store/fivem-titan",
    description: {
      ram: "16GB",
      cores: "8 núcleos",
      ssd: "100GB",
      attrs: [
        "Anti-DDoS Incluído",
        "Painel de Controle",
        "Suporte 24/7",
        "Instalação Gratuita",
        "Até 256 jogadores",
        "Backup Semanal",
        "Uptime 99.9%",
        "Prioridade no Suporte",
        "Migração Gratuita",
        "IP Dedicado",
        "Consultoria Especializada",
      ],
    },
  },
]
