export const plans = [
  {
    name: "FiveM Start",
    price: "84,90",
    link: "https://app.neonhost.com.br/index.php?rp=/store/vps-fivem/vps-fivem-1",
    description: {
      ram: "2GB",
      cores: "2 núcleos",
      ssd: "45GB",
      attrs: [
        "Anti-DDoS Incluído",
        "Painel de Controle",
        "Suporte 24/7",
        "Instalação Gratuita",
        "Até 32 jogadores",
        "Uptime 99.9%",
      ],
    },
  },
  {
    name: "FiveM Plus",
    price: "126,90",
    link: "https://app.neonhost.com.br/index.php?rp=/store/vps-fivem/vps-fivem-2",
    description: {
      ram: "4GB",
      cores: "2 núcleos",
      ssd: "50GB",
      attrs: [
        "Anti-DDoS Incluído",
        "Painel de Controle",
        "Suporte 24/7",
        "Instalação Gratuita",
        "Até 64 jogadores",
        "Backup Semanal",
        "Uptime 99.9%",
      ],
    },
  },
  {
    name: "FiveM Pro",
    price: "198,90",
    link: "https://app.neonhost.com.br/index.php?rp=/store/vps-fivem/vps-fivem-3",
    description: {
      ram: "6GB",
      cores: "3 núcleos",
      ssd: "60GB",
      attrs: [
        "Anti-DDoS Incluído",
        "Painel de Controle",
        "Suporte 24/7",
        "Instalação Gratuita",
        "Até 96 jogadores",
        "Backup Semanal",
        "Uptime 99.9%",
        "Prioridade no Suporte",
      ],
    },
  },
  {
    name: "FiveM Ultra",
    price: "246,90",
    link: "https://app.neonhost.com.br/index.php?rp=/store/vps-fivem/vps-fivem-4",
    description: {
      ram: "8GB",
      cores: "4 núcleos",
      ssd: "70GB",
      attrs: [
        "Anti-DDoS Incluído",
        "Painel de Controle",
        "Suporte 24/7",
        "Instalação Gratuita",
        "Até 128 jogadores",
        "Backup Semanal",
        "Uptime 99.9%",
        "Prioridade no Suporte",
        "Migração Gratuita",
      ],
    },
  },
  {
    name: "FiveM Extreme",
    price: "289,90",
    link: "https://app.neonhost.com.br/index.php?rp=/store/vps-fivem/vps-fivem-5",
    description: {
      ram: "10GB",
      cores: "6 núcleos",
      ssd: "80GB",
      attrs: [
        "Anti-DDoS Incluído",
        "Painel de Controle",
        "Suporte 24/7",
        "Instalação Gratuita",
        "Até 196 jogadores",
        "Backup Semanal",
        "Uptime 99.9%",
        "Prioridade no Suporte",
        "Migração Gratuita",
        "IP Dedicado",
      ],
    },
  },
  {
    name: "FiveM Titan",
    price: "362,90",
    link: "https://app.neonhost.com.br/index.php?rp=/store/vps-fivem/vps-fivem-6",
    description: {
      ram: "12GB",
      cores: "8 núcleos",
      ssd: "90GB",
      attrs: [
        "Anti-DDoS Incluído",
        "Painel de Controle",
        "Suporte 24/7",
        "Instalação Gratuita",
        "Até 256 jogadores",
        "Backup Semanal",
        "Uptime 99.9%",
        "Prioridade no Suporte",
        "Migração Gratuita",
        "IP Dedicado",
      ],
    },
  },
  {
    name: "FiveM Elite",
    price: "429,90",
    link: "https://app.neonhost.com.br/index.php?rp=/store/vps-fivem/vps-fivem-7",
    description: {
      ram: "16GB",
      cores: "8 núcleos",
      ssd: "100GB",
      attrs: [
        "Anti-DDoS Incluído",
        "Painel de Controle",
        "Suporte 24/7",
        "Instalação Gratuita",
        "Até 256 jogadores",
        "Backup Semanal",
        "Uptime 99.9%",
        "Prioridade no Suporte",
        "Migração Gratuita",
        "IP Dedicado",
      ],
    },
  },
  {
    name: "FiveM Neon",
    price: "429,90",
    link: "https://app.neonhost.com.br/index.php?rp=/store/vps-fivem/vps-fivem-8",
    description: {
      ram: "20GB",
      cores: "8 núcleos",
      ssd: "150GB",
      attrs: [
        "Anti-DDoS Incluído",
        "Painel de Controle",
        "Suporte 24/7",
        "Instalação Gratuita",
        "Até 256 jogadores",
        "Backup Semanal",
        "Uptime 99.9%",
        "Prioridade no Suporte",
        "Migração Gratuita",
        "IP Dedicado",
      ],
    },
  },
]
