import { Footer } from "@/components/footer";
import { NavbarComponent } from "@/components/navbar";
import HelpSystem from "@/components/help-system"
import Script from "next/script";
import { siteConfig } from "@/config/site";
import "@/styles/globals.css";
import clsx from "clsx";
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
	title: {
		default: "Hospedagem de Jogos no Brasil | NeonHost",
		template: `%s - ${siteConfig.name}`,
	},
	description:
		"Oferecemos VPS Gamer com processadores AMD Ryzen e proteção Anti DDoS, ideais para servidores de jogos e aplicações de alto desempenho.",
	applicationName: "NeonHost",
    creator: "NeonHost",
    publisher: "NeonHost",
    themeColor: "#0A0C10",
    manifest: "/manifest.json",
    robots: {
		index: true,
		follow: true,
		nosnippet: false,
		noarchive: false,
		nocache: false,
		noimageindex: false,
	},
keywords: [
    "NeonHost",
    "Host",
    "BrasilFivemHost",
    "FiveM Host",
    "BBHost",
    "WyzeHost",
    "TynaHost",
    "Hostinger",
    "DokeHost",
    "HeavyHost",
    "OminiHost",
    "BH Servers",
    "Ultahost",
    "KnownHost",
    "Linode",
    "DigitalOcean",
    "Azure",
    "Namecheap",
    "NetEarthOne",
    "FlameHost",
    "RazeHost",
    "Loding Hosting",
    "Nice Hosting",
    "VPS Neon",
    "VPS Brasil",
    "Proteção Anti DDoS",
    "Servidor de Minecraft",
    "Servidor de FiveM",
    "Servidor de Rust",
    "Hospedagem de jogos no Brasil",
    "Servidor dedicado para jogos",
    "Servidor de ARK",
    "Servidor de Satisfactory",
    "VPS para jogos",
    "Servidores dedicados Brasil",
    "Gaming VPS",
    "FiveM VPS",
    "Minecraft VPS",
    "VPS com NVMe",
    "Servidor de Counter Strike",
    "Servidor de CS:GO",
    "Servidor de GTA RP",
    "Servidor de Unturned",
    "VPS Linux",
    "VPS Windows",
    "Servidor com proteção DDoS",
    "Cloud Gaming",
    "Hospedagem de jogos multiplayer",
    "Servidor dedicado gamer",
    "Servidor de Minecraft Brasil",
    "VPS com alta performance",
    "VPS barato",
    "VPS para trading",
    "Servidor dedicado NVMe",
    "Cloud Hosting",
    "Wyze host",
    "Host",
    "DDoS",
    "Webhost",
    "Hospedagem",
    "VPS",
    "VPS",
    "VPS Gamer",
    "Semi Dedicado",
    "Servidor Dedicado",
    "TeamSpeak",
    "TeamSpeak 3 server",
    "Proteção DDoS",
    "Server",
    "Servidor",
    "Serviço de hospedagem",
    "Hospedagem Brasil",
    "Host brasileira",
    "Host 0ms",
    "Melhor host do Brasil",
    "Onde hospedar",
    "Como hospedar um site",
    "Como hospedar FiveM",
    "Host de jogo",
    "VRising",
    "Como criar servidor de VRising",
    "Como criar servidor de GTA RP",
    "Como criar servidor de FiveM",
    "Como criar servidor de cidade FiveM",
    "Como criar servidor de cidade FiveM RP",
    "Jogar VRising online",
    "VRising online",
    "Melhor servidor VRising",
    "VRising server",
    "Host FiveM",
    "Hospedagem de FiveM",
    "FiveM",
    "Host Minecraft",
    "Hospedagem Minecraft",
    "Minecraft",
    "Como deixar FiveM online 24 horas",
    "Criar cidade FiveM",
    "Cidade",
    "Host de GTA RP",
    "Hospedagem para GTA RP",
    "Host FiveM BR",
    "Anti-DDoS",
    "Hostzone",
    "Cache externo",
    "Cache externo FiveM",
    "Cache externo GTA RP",
    "Cache externo VPS",
    "Cache externo VPS Gamer",
    "Cache externo RedM",
    "Cache externo RDR2",
    "Host de RedM",
    "VPS RedM",
    "VPS RDR2",
    "Servidor VPS Gamer",
    "Servidor Gamer",
    "Steam",
    "Steam Games",
    "Steam VPS",
    "VPS Azure",
    "Google Cloud",
    "Comprar VPS",
    "Servidor VPS Brasil",
    "VPS Windows barato",
    "Melhor VPS 2025",
    "VPS vs dedicado",
    "VPS Cloud Brasil",
    "VPS São Paulo",
    "VPS Rio de Janeiro",
    "Datacenter Brasil",
    "Hospedagem servidor Minecraft",
    "Servidor Minecraft barato",
    "Free Minecraft server hosting",
    "Hospedagem FiveM",
    "VPS FiveM DDoS",
    "Servidor Rust Brasil",
    "Servidor ARK Brasil",
    "ARK server hosting",
    "Valheim server brasileiro",
    "Como criar servidor Minecraft 24/7 VPS",
    "VPS Linux para jogos com painel Pterodactyl",
    "VPS gamer com proteção DDoS grátis",
    "Comprar VPS barato com ping baixo Brasil",
    "VPS FiveM barato",
    "Hospedagem FiveM DDoS",
    "VPS para GTA RP",
    "VPS RedM Brasil",
    "VPS para RedM",
    "Hospedar servidor RedM",
    "Como criar servidor FiveM com VPS",
    "Melhor VPS para FiveM 2025",
    "VPS com proteção DDoS para GTA RP",
    "Hospedagem RedM com painel TXAdmin",
    "VPS FiveM ping baixo Brasil",
    "Top 10 melhores host FiveM",
    "Top 10 melhores VPS gamer",
    "As top 10 melhores VPS gamer",
    "As top 10 melhores VPS FiveM",
    "As top 10 melhores host FiveM",
    "Melhores VPS FiveM",
    "Melhores VPS FiveM Brasil",
    "Melhores VPS FiveM Brasil 2024",
    "Melhores VPS FiveM Brasil 2025",
    "Melhores VPS Gamer",
    "Melhores VPS Gamer Brasil",
    "Melhores VPS Gamer Brasil 2024",
    "Melhores VPS Gamer Brasil 2025",
    "Melhores VPS 2024",
    "Melhores VPS Brasil",
    "Servidores Dedicados",
    "Servidores Dedicados Brasil 2024",
    "Servidores Dedicados Brasil 2025",
    "Host Rust",
    "Host Rust Brasil",
    "Host Rust Brasil 2024",
    "Host Rust Brasil 2025",
    "Host Terraria Brasil 2025",
    "Host Terraria Brasil 2024",
    "Host Terraria Brasil",
    "Host Terraria",
    "Host Minecraft Brasil",
    "Host Minecraft Brasil 2024",
    "Host Minecraft Brasil 2025",
    "VPS gamer Brasil",
    "VPS gamer Brasil 2024",
    "VPS gamer Brasil 2025",
    "FiveM Brasil",
    "FiveM Brasil 2024",
    "FiveM Brasil 2025",
    "FiveM host Brasil",
    "FiveM host Brasil 2024",
    "FiveM host Brasil 2025",
    "VPS para FiveM Brasil",
    "VPS para jogos Brasil",
    "VPS para jogos Brasil 2024",
    "VPS para jogos Brasil 2025",
    "Host para DayZ",
    "Host para DayZ Brasil",
    "Host para DayZ Brasil 2024",
    "Host para DayZ Brasil 2025",
    "Cloud VPS",
    "Cloud VPS Brasil",
    "Cloud VPS Brasil 2024",
    "Cloud VPS Brasil 2025",
    "Cloud VPS gamer",
    "Cloud VPS gamer Brasil",
    "Cloud VPS gamer Brasil 2024",
    "Cloud VPS gamer Brasil 2025",
    "Host para Ragnarok",
    "Host para Ragnarok Brasil",
    "Host para Ragnarok Brasil 2024",
    "Host para Ragnarok Brasil 2025",
    "BB Host",
    "Host de jogos",
    "Host de jogos Brasil",
    "Host de jogos Brasil 2024",
    "Host de jogos Brasil 2025",
    "Host para jogos",
    "Host para jogos Brasil",
    "Host para jogos Brasil 2024",
    "Host para jogos Brasil 2025",
    "FiveM host Brasil",
    "FiveM host Brasil 2024",
    "FiveM host Brasil 2025",
    "Host FiveMBrasil",
    "FiveM Brasil host",
    "Host para ARK",
    "VPS no Brasil",
    "Servidores",
    "Servidores VPS",
    "Servidores VPS Brasil",
    "VPS barata",
    "Virtual máquina",
    "Virtual máquina Brasil",
    "Virtual máquina Brasil 2024",
    "Virtual máquina Brasil 2025",
    "Anti DDoS Brasil",
    "Anti DDoS Brasil 2024",
    "Anti DDoS Brasil 2025",
    "Antiddos",
    "Melhor proteção para FiveM",
    "Melhor proteção para FiveM Brasil",
    "Melhor proteção para FiveM Brasil 2024",
    "Melhor proteção para FiveM Brasil 2025",
    "GTA V host",
    "GTA host",
    "GTA host Brasil",
    "GTA host Brasil 2024",
    "GTA host Brasil 2025",
    "MTA host",
    "MTA",
    "MTA Brasil 2024",
    "MTA Brasil 2025",
    "Dedicado",
    "Baremetal",
    "Baremetal Brasil",
    "Baremetal Brasil 2024",
    "Baremetal Brasil 2025",
    "Datacenter BR",
    "Datacenter BR 2024",
    "Datacenter BR 2025",
    "Brasil",
    "O que é VPS",
    "TacoHost",
    "Servidores na nuvem",
    "Neopixelhost",
    "Cloud server",
    "Servidor Tibia",
    "Servidor WoW",
    "Servidor Mu Online",
    "Hospedagem de streaming",
    "Host GTA RP",
    "Servidor ARK",
    "Blasthosting",
    "Hospedagem de site",
    "Hospedagem cPanel",
    "Hospedagem barata",
    "Hospedagem com cPanel",
    "Melhor hospedagem de site",
    "Hospedagem de site confiável",
    "Hospedagem rápida",
    "Servidor web",
    "Servidor web barato",
    "Servidores dedicados no Brasil",
    "Servidor dedicado barato",
    "Servidor dedicado com proteção DDoS",
    "Servidor dedicado de alto desempenho",
    "Servidores VPS no Brasil",
    "Servidores VPS baratos",
    "VPS para hospedagem",
    "VPS de alta performance",
    "VPS para bot",
    "VPS para Discord",
    "VPS para Roblox",
    "Proteção AntiDDoS no Brasil",
    "Proteção DDoS para jogos",
    "Proteção DDoS para servidores",
    "DDoS mitigation",
    "Proteção contra ataques DDoS",
    "Firewall DDoS",
    "Segurança para servidores",
    "Mitigação DDoS para Minecraft",
    "Proteção DDoS dedicada",
    "Hospedagem para jogos online",
    "Melhor hospedagem para jogos",
    "Servidor de jogos",
    "Servidor para jogos",
    "Hospedagem de games",
    "Host de jogos barato",
    "Game hosting",
    "Game server",
    "Hospedagem de Minecraft",
    "Host de Minecraft barato",
    "Hospedagem de Minecraft barata",
    "Hospedagem Minecraft 24h",
    "Servidor Minecraft",
    "VPS para Minecraft",
    "Host Minecraft ping baixo",
    "Servidor dedicado Minecraft",
    "Servidor Minecraft barato",
    "Hospedagem Minecraft no Brasil",
    "Hospedagem de Minecraft com mods",
    "Hospedagem de Minecraft grátis",
    "Servidor Minecraft com DDoS protection",
    "Hospedagem SAMP",
    "Host SAMP",
    "Servidor SAMP",
    "SAMP host",
    "Servidor SAMP barato",
    "Hospedagem MTA",
    "Host MTA",
    "Servidor MTA",
    "Servidor SAMP com proteção DDoS",
    "Hospedagem de Ragnarok",
    "Servidor de Ragnarok",
    "Host Ragnarok",
    "Hospedagem Ragnarök",
    "Ragnarok host barato",
    "Servidor Ragnarok dedicado",
    "Servidor FiveM",
    "Hospedagem ARK",
    "Host Rust",
    "Servidor CS:GO",
    "Hospedagem de CS:GO",
    "Servidor Valorant",
    "Hospedagem Valorant",
    "Servidor LoL",
    "Hospedagem de rádio",
    "Revenda de streaming",
    "Revenda de rádio",
    "Rádio online",
    "Streaming para rádio",
    "Ecxon",
    "Ecxonhost",
    "Ecxon hosting",
    "Ecxonhost.com",
    "Ecxonhost.net",
    "Virtu",
    "Virtuahost",
    "Virtualhost",
    "Host brasileiro",
    "Melhor host brasileiro",
    "Hospedagem confiável",
    "Hospedagem com proteção",
    "Hospedagem gamer",
    "Melhor hospedagem gamer",
    "Servidores gamer",
    "Servidores cloud",
    "Host de jogos sem lag",
    "Servidor FiveM com ping baixo",
    "VPS gamer com latência mínima",
    "Como escolher um VPS para jogos",
    "Hospedagem FiveM otimizada",
    "Servidor Minecraft para mods",
    "VPS para stream de jogos",
    "Hospedagem com suporte 24h",
    "Servidor para campeonatos eSports",
    "Diferença entre VPS e Servidor Dedicado para jogos",
    "Migrar servidor de jogos",
    "Configurar VPS FiveM",
    "Segurança para servidor de FiveM",
    "Servidor de jogos com CPU de alta performance",
    "Hospedagem FiveM barata e de qualidade",
    "Servidor de testes FiveM",
    "Planos de hospedagem FiveM",
    "Melhor custo benefício VPS gamer",
    "Dedicado para servidores de comunidade",
    "Servidor de Valheim no Brasil",
    "Servidor de Palworld no Brasil",
    "Servidor de V Rising no Brasil",
    "Servidor de Conan Exiles no Brasil",
    "Servidor de Ark Survival Ascended",
    "Suporte FiveM",
    "FiveM scripts",
    "Hospedagem com painel de controle fácil",
    "Servidor de jogos fácil de configurar",
  ],
	openGraph: {
		title: "Hospedagem de Jogos no Brasil | NeonHost",
		description:
			"Hospedagem de alto desempenho, com baixa latência, infraestrutura no Brasil, armazenamento NVMe e proteção anti-DDoS para jogos como Minecraft, FiveM e muito mais.",
		url: "https://neonhost.com.br/",
		siteName: "NeonHost",
		images: [
		    {
		        url: "/favicon.ico",
		        // width: 1200,
		        // height: 630,
		        alt: "NeonHost - Servidores Dedicados",
		    },
		],
	},
	twitter: {
		card: "summary_large_image",
		title: "Hospedagem de Jogos no Brasil | NeonHost",
		description:
			"Desempenho superior e segurança com infraestrutura no Brasil. Hospede seus servidores de Minecraft, FiveM e outros jogos com proteção Anti DDoS.",
		images: [
		    {
		        url: "/favicon.ico",
		        // width: 1200,
		        // height: 630,
		        alt: "NeonHost - Servidores Dedicados",
		    },
		],
	},
	icons: {
		icon: "/favicon.ico",
	},
};

export const viewport: Viewport = {
	themeColor: [
		{ media: "(prefers-color-scheme: light)", color: "white" },
		{ media: "(prefers-color-scheme: dark)", color: "black" },
	],
};

const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="pt-BR" suppressHydrationWarning>

<Script
          id="gtm-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-NLK4RWTG');
            `,
          }}
        />
			<meta
				name="google-site-verification"
				content="hsbqhlsa_EF36270POQ4hf418PvGn0QT3CcCRkw1fRE"
			/>
			<head />
			<body
				className={clsx("min-h-screen dark text-gray-100", inter.className)}
			>
				<div className="relative flex flex-col">
					<div className="border-b border-b-gray-700">
						<NavbarComponent />
					</div>
					<main className="bg-[#0A0C10]">{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}