import type React from "react"
import type { Metadata, Viewport } from "next"
import { siteConfig } from "@/config/site"
import ClientLayout from "./ClientLayout"

export const metadata: Metadata = {
  title: {
    default: "Hospedagem de Jogos no Brasil | NeonHost",
    template: `%s - ${siteConfig.name}`,
  },
  description:
    "Oferecemos VPS Gamer com processadores AMD Ryzen e proteção Anti DDoS, ideais para servidores de jogos e aplicações de alto desempenho.",
  keywords: [
    "NeonHost",
    "BrasilFivemHost",
    "fivemhost",
    "Fivem Host",
    "bbhost",
    "BBHost",
    "BBHOST",
    "WyzeHost",
    "TynaHost",
    "Hostinger",
    "DokeHost",
    "HeavyHost",
    "OminiHost",
    "BH Servers",
    "Ultahost",
    "KnownHost",
    "Linode",
    "DigitalOcean",
    "Azure",
    "Namecheap",
    "NetEarthOne",
    "FlameHost",
    "RazeHost",
    "Loding Hosting",
    "Nice Hosting",
    "VPS Neon",
    "VPS Brasil",
    "Proteção Anti DDoS",
    "servidor de Minecraft",
    "servidor de FiveM",
    "servidor de Rust",
    "hospedagem de jogos no Brasil",
    "servidor dedicado para jogos",
    "servidor de ARK",
    "servidor de Satisfactory",
    "VPS para jogos",
    "servidores dedicados Brasil",
    "gaming VPS",
    "FiveM VPS",
    "Minecraft VPS",
    "VPS com NVMe",
    "servidor de Counter Strike",
    "servidor de CS:GO",
    "servidor de GTA RP",
    "servidor de Unturned",
    "VPS Linux",
    "VPS Windows",
    "servidor com proteção DDoS",
    "cloud gaming",
    "hospedagem de jogos multiplayer",
    "servidor dedicado gamer",
    "servidor de Minecraft Brasil",
    "VPS com alta performance",
    "VPS barato",
    "VPS para trading",
    "servidor dedicado NVMe",
    "cloud hosting",
    "FlameHost",
    "RazeHost",
    "Loding Hosting",
    "Nice Hosting",
    "wyze",
    "wyze host",
    "host",
    "ddos",
    "webhost",
    "hospedagem",
    "site",
    "vps",
    "vps gamer",
    "gaming vps",
    "vps",
    "semi dedicado",
    "servidor dedicado",
    "teamspeak",
    "team-speak",
    "team-speak 3 server",
    "proteção ddos",
    "server",
    "servidor",
    "servidor",
    "serviço de hospedagem",
    "hospedagem brasil",
    "host brasileira",
    "host 0ms",
    "melhor host do brasil",
    "onde hospedar",
    "como hospedar um site",
    "como hospedar um site",
    "como hospedar fivem",
    "host de jogo",
    "vrising",
    "como criar servidor de vrising",
    "como criar servidor de gta rp",
    "como criar servidor de fivem",
    "como criar servidor de cidade fivem",
    "como criar servidor de cidade fivem rp",
    "jogar vrising online",
    "vrising online",
    "melhor servidor vrising",
    "vrising server",
    "host fivem",
    "hospedagem de fivem",
    "fivem",
    "host minecraft",
    "hospedagem minecraft",
    "minecraft",
    "como deixar fivem online 24 horas",
    "criar cidade fivem",
    "cidade",
    "host de fivem",
    "host gta rp",
    "hospedagem para gta rp",
    "host fivem br",
    "fivem host",
    "ddos",
    "proteção ddos",
    "anti-ddos",
    "Hostzone",
    "Hostinger",
    "HeavyHost",
    "BH Servers",
    "Ultahost",
    "KnownHost",
    "Linode",
    "DigitalOcean",
    "Azure",
    "Namecheap",
    "NetEarthOne",
    "FlameHost",
    "RazeHost",
    "Loding Hosting",
    "Nice Hosting",
    "VPS Neon",
    "VPS Brasil",
    "Proteção Anti DDoS",
    "servidor de Minecraft",
    "servidor de FiveM",
    "servidor de Rust",
    "hospedagem de jogos no Brasil",
    "servidor dedicado para jogos",
    "servidor de ARK",
    "servidor de Satisfactory",
    "VPS para jogos",
    "servidores dedicados Brasil",
    "gaming VPS",
    "FiveM VPS",
    "Minecraft VPS",
    "VPS com NVMe",
    "servidor de Counter Strike",
    "servidor de CS:GO",
    "servidor de GTA RP",
    "servidor de Unturned",
    "VPS Linux",
    "VPS Windows",
    "servidor com proteção DDoS",
    "cloud gaming",
    "hospedagem de jogos multiplayer",
    "servidor dedicado gamer",
    "servidor de Minecraft Brasil",
    "VPS com alta performance",
    "VPS barato",
    "VPS para trading",
    "servidor dedicado NVMe",
    "cloud hosting",
    "cache externo",
    "cache externo fivem",
    "cache externo gtarp",
    "cache-externo",
    "cache-externo fivem",
    "cache-externo gtarp",
    "cache-externo vps",
    "cache-externo vps gamer",
    "cache externo vps",
    "cache externo vps gamer",
    "cache externo redm",
    "cache externo rd2",
    "host de redm",
    "vps redm",
    "vps rd2",
    "Vps Redm",
    "Vps Gamer",
    "Vps gamer",
    "vps gamer",
    "Servidor VPS Gamer",
    "Servidor Vps Gamer",
    "Servidor Gamer",
    "Steam",
    "Steam Games",
    "Steam VPS",
    "VPS Azure",
    "Google Cloud",
    "vps barato",
    "comprar vps",
    "servidor vps brasil",
    "vps windows barato",
    "melhor vps 2025",
    "vps vs dedicado",
    "vps cloud brasil",
    "vps são paulo",
    "vps rio de janeiro",
    "datacenter brasil",
    "hospedagem servidor minecraft",
    "servidor minecraft barato",
    "free minecraft server hosting",
    "hospedagem fivem",
    "vps fivem ddos",
    "servidor gta rp host",
    "servidor rust brasil",
    "ark server hosting",
    "valheim server brasileiro",
    "game server hosting",
    "low latency vps",
    "ddos protection gamer",
    "como criar servidor minecraft 24/7 vps",
    "vps linux para jogos com painel pterodactyl",
    "vps gamer com proteção ddos grátis",
    "comprar vps barato com ping baixo brasil",
  ],

  openGraph: {
    title: "Hospedagem de Jogos no Brasil | NeonHost",
    description:
      "Hospedagem de alto desempenho, com baixa latência, infraestrutura no Brasil, armazenamento NVMe e proteção anti-DDoS para jogos como Minecraft, FiveM e muito mais.",
    url: "https://neonhost.com.br/",
    siteName: "NeonHost",
    images: [
      {
        url: "/favicon.ico",
        // width: 1200,
        // height: 630,
        alt: "NeonHost - Servidores Dedicados",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Hospedagem de Jogos no Brasil | NeonHost",
    description:
      "Desempenho superior e segurança com infraestrutura no Brasil. Hospede seus servidores de Minecraft, FiveM e outros jogos com proteção Anti DDoS.",
    images: [
      {
        url: "/favicon.ico",
        // width: 1200,
        // height: 630,
        alt: "NeonHost - Servidores Dedicados",
      },
    ],
  },
  icons: {
    icon: "/favicon.ico",
  },
}

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <ClientLayout>{children}</ClientLayout>
}
